services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: dev-cluster
      CASSANDRA_DC: dc1
    volumes:
      - cassandra_data:/var/lib/cassandra

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: go-keycloack-app
    ports:
      - "3000:3000"
    depends_on:
      - cassandra
      - valkey
    environment:
      - CASSANDRA_HOST=cassandra
      - VALKEY_HOST=valkey
    restart: unless-stopped

volumes:
  cassandra_data:
